from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from ingest_srd35 import run_fixture_ingestion, write_golden_outputs
else:
    from scripts.ingest_srd35 import run_fixture_ingestion, write_golden_outputs


def _snippet(text: str, max_lines: int = 8) -> str:
    lines = text.strip().splitlines()
    clipped = lines[:max_lines]
    if len(lines) > max_lines:
        clipped.append("...")
    return "\n".join(clipped)


def build_preview_markdown(repo_root: Path, evidence: dict) -> str:
    fixture_root = repo_root / "tests" / "fixtures" / "srd_35"
    fixture_files = sorted(fixture_root.glob("*.rtf"))
    canonical_report = evidence["canonical_report"]
    canonical_map = evidence["canonical"]

    lines = [
        "# Fixture Ingestion Preview",
        "",
        "Generated by `python scripts/preview_fixtures.py`.",
        "",
    ]

    for fixture in fixture_files:
        lines.append(f"## {fixture.name}")
        lines.append("")
        lines.append("### Raw RTF Snippet")
        lines.append("```rtf")
        lines.append(_snippet(fixture.read_text(encoding='utf-8')))
        lines.append("```")
        lines.append("")

        extracted_name = f"{fixture.stem.lower().replace('-', '_')}.txt"
        extracted_text = evidence["extracted"].get(extracted_name, "")
        lines.append("### Extracted Text")
        lines.append("```text")
        lines.append(_snippet(extracted_text, max_lines=12))
        lines.append("```")
        lines.append("")

        related = [r for r in canonical_report["records"] if r["source_location"].startswith(fixture.name)]
        lines.append(f"### Canonical Sections ({len(related)})")
        lines.append("")
        for record in related:
            payload = canonical_map[Path(record["canonical_path"]).name]
            lines.append(f"- document_id: `{payload['document_id']}`")
            lines.append(f"- section_path: `{payload['locator']['section_path']}`")
            lines.append(f"- source_location: `{payload['locator']['source_location']}`")
            lines.append("- content preview:")
            lines.append("```text")
            lines.append(_snippet(payload["content"], max_lines=6))
            lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate fixture ingestion preview and optional golden outputs.")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root.",
    )
    parser.add_argument(
        "--update-golden",
        action="store_true",
        help="Rewrite tests/fixtures/expected outputs from current fixture ingestion behavior.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    repo_root = args.repo_root.resolve()
    evidence = run_fixture_ingestion(repo_root)

    if args.update_golden:
        write_golden_outputs(repo_root, evidence)

    preview_md = build_preview_markdown(repo_root, evidence)
    preview_path = repo_root / "tests" / "fixtures" / "PREVIEW.md"
    preview_path.write_text(preview_md, encoding="utf-8")
    print(f"Wrote {preview_path}")
    if args.update_golden:
        print("Updated tests/fixtures/expected/{extracted,canonical}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
